Materi 1: Menyertakan Prefix dan Suffix pada seluruh Kolom Data Frame

Import Modules

In [ ]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.3.5

Persiapan Data Frame

In [ ]:
n_rows = 5
n_cols = 5
cols = tuple('ABCDE')

df = pd.DataFrame(np.random.randint(1, 10, size=(n_rows, n_cols)), 
                  columns=cols)
df

   A  B  C  D  E
0  7  5  6  7  4
1  4  3  4  8  2
2  2  4  8  8  8
3  7  8  1  1  7
4  3  5  5  3  9

In [ ]:
tuple('ABCDE')

('A', 'B', 'C', 'D', 'E')

Menyertakan Prefix Kolom

In [ ]:
df.add_prefix('kolom_')

   kolom_A  kolom_B  kolom_C  kolom_D  kolom_E
0        7        5        6        7        4
1        4        3        4        8        2
2        2        4        8        8        8
3        7        8        1        1        7
4        3        5        5        3        9

Menyertakan Suffix Kolom

In [ ]:
df.add_suffix('_field')

   A_field  B_field  C_field  D_field  E_field
0        7        5        6        7        4
1        4        3        4        8        2
2        2        4        8        8        8
3        7        8        1        1        7
4        3        5        5        3        9

Materi 2: Pemilihan Baris (Rows Selection) pada Data Frame

Import Modules

In [ ]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.3.5

Persiapan Data Frame

In [ ]:
n_rows = 10
n_cols = 5
cols = tuple('ABCDE')

df = pd.DataFrame(np.random.randint(1, 5, size=(n_rows, n_cols)), 
                  columns=cols)
df

   A  B  C  D  E
0  2  2  2  1  1
1  1  2  3  3  3
2  2  2  2  2  1
3  3  4  3  4  4
4  3  4  4  1  3
5  3  1  3  2  2
6  3  4  4  1  4
7  4  4  3  4  4
8  1  4  2  3  1
9  1  2  3  3  4

Selection dengan Operator Logika |

In [ ]:
df[(df['A'] == 1) | (df['A'] == 3)]

   A  B  C  D  E
1  1  2  3  3  3
3  3  4  3  4  4
4  3  4  4  1  3
5  3  1  3  2  2
6  3  4  4  1  4
8  1  4  2  3  1
9  1  2  3  3  4

Selection dengan Fungsi isin()

In [ ]:
df[df['A'].isin([1, 3])]

   A  B  C  D  E
1  1  2  3  3  3
3  3  4  3  4  4
4  3  4  4  1  3
5  3  1  3  2  2
6  3  4  4  1  4
8  1  4  2  3  1
9  1  2  3  3  4

Mengenal Operator Negasi ~

In [ ]:
df[~df['A'].isin([1, 3])]

   A  B  C  D  E
0  2  2  2  1  1
2  2  2  2  2  1
7  4  4  3  4  4

Materi 3: Konversi Tipe Data String ke Numerik pada Kolom Data Frame

Import Modules

In [ ]:
import pandas as pd

print(pd.__version__)

2.3.3

Persiapan Data Frame

In [ ]:
data = {'col1':['1', '2', '3', 'teks'], 
        'col2':['1', '2', '3', '4']}

df = pd.DataFrame(data)
df

   col1 col2
0     1    1
1     2    2
2     3    3
3  teks    4

In [ ]:
df.dtypes

col1    object
col2    object
dtype: object

Konversi Tipe Data dengan Fungsi astype()

In [ ]:
df_x = df.astype({'col2':'int'})
df_x

   col1  col2
0     1     1
1     2     2
2     3     3
3  teks     4

In [ ]:
df_x.dtypes

col1    object
col2     int64
dtype: object

Konversi Tipe Data Numerik dengan Fungsi to_numeric()

In [ ]:
df.apply(pd.to_numeric, errors='coerce')

   col1  col2
0   1.0     1
1   2.0     2
2   3.0     3
3   NaN     4

Materi 4: Pemilihan Kolom (Columns Selection) pada Data Frame berdasarkan Tipe Data

Import Modules

In [ ]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.3.5

Persiapan Data Frame

In [ ]:
n_rows = 5
n_cols = 2
cols = ['bil_pecahan', 'bil_bulat']

df = pd.DataFrame(np.random.randint(1, 20, size=(n_rows, n_cols)), columns=cols)

df['bil_pecahan'] = df['bil_pecahan'].astype('float')

df.index = pd.date_range(start='2024-10-01', periods=n_rows, freq='h')

df = df.reset_index()
df['teks'] = list('ABCDE')

df

                index  bil_pecahan  bil_bulat teks
0 2024-10-01 00:00:00          2.0          2    A
1 2024-10-01 01:00:00          6.0         10    B
2 2024-10-01 02:00:00         11.0          8    C
3 2024-10-01 03:00:00         12.0          9    D
4 2024-10-01 04:00:00          4.0         10    E

In [ ]:
df.dtypes

index          datetime64[ns]
bil_pecahan           float64
bil_bulat               int32
teks                   object
dtype: object

Memilih Kolom Bertipe Data Numerik

In [ ]:
df.select_dtypes(include='number')

   bil_pecahan  bil_bulat
0          2.0          2
1          6.0         10
2         11.0          8
3         12.0          9
4          4.0         10

In [ ]:
df.select_dtypes(include='float')

   bil_pecahan
0          2.0
1          6.0
2         11.0
3         12.0
4          4.0

In [ ]:
df.select_dtypes(include='int')

   bil_bulat
0          2
1         10
2          8
3          9
4         10

Memilih Kolom Bertipe Data string atau object

In [ ]:
df.select_dtypes(include='object')

  teks
0    A
1    B
2    C
3    D
4    E

Memilih Kolom Bertipe Data datetime

In [ ]:
df.select_dtypes(include='datetime')

                index
0 2024-10-01 00:00:00
1 2024-10-01 01:00:00
2 2024-10-01 02:00:00
3 2024-10-01 03:00:00
4 2024-10-01 04:00:00

Memilih Kolom dengan Kombinasi Tipe Data

In [ ]:
df.select_dtypes(include=['number', 'object'])

   bil_pecahan  bil_bulat teks
0          2.0          2    A
1          6.0         10    B
2         11.0          8    C
3         12.0          9    D
4          4.0         10    E