Materi 21: Melakukan agregasi menggunakan agg()

Import Modules

In [1]:
import pandas as pd

print(pd.__version__)

2.3.3

Persiapan Data Frame

In [6]:
df = pd.read_csv("../Matplotlib/Iris.csv")
df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

Mengenal groupby() dan fungsi agregasi

In [7]:
df.groupby('Species')['PetalLengthCm'].count().to_frame()

                 PetalLengthCm
Species
Iris-setosa                 50
Iris-versicolor             50
Iris-virginica              50

In [8]:
df.groupby('Species')['PetalLengthCm'].mean().to_frame()

                 PetalLengthCm
Species
Iris-setosa              1.464
Iris-versicolor          4.260
Iris-virginica           5.552

In [9]:
df.groupby('Species')['PetalLengthCm'].median().to_frame()

                 PetalLengthCm
Species
Iris-setosa               1.50
Iris-versicolor           4.35
Iris-virginica            5.55

Agregasi dengan agg()

In [10]:
df.groupby('Species')['PetalLengthCm'].agg(['count', 'mean', 'median'])

                 count   mean  median
Species
Iris-setosa         50  1.464    1.50
Iris-versicolor     50  4.260    4.35
Iris-virginica      50  5.552    5.55

Agregasi dengan describe()

In [11]:
df.groupby('Species')['PetalLengthCm'].describe()

                 count   mean       std  min  25%   50%    75%  max
Species
Iris-setosa       50.0  1.464  0.173511  1.0  1.4  1.50  1.575  1.9
Iris-versicolor   50.0  4.260  0.469911  3.0  4.0  4.35  4.600  5.1
Iris-virginica    50.0  5.552  0.551895  4.5  5.1  5.55  5.875  6.9

Materi 22: Memantau penggunaan memory suatu Data Frame

Import Modules

In [12]:
import pandas as pd

print(pd.__version__)

2.3.3

Persiapan Data Frame

In [18]:
df_titanic = pd.read_csv("titanicfull.csv")
df_titanic.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S

In [21]:
df_iris = pd.read_csv("../Matplotlib/Iris.csv")
df_iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

Memantau penggunaan memory suatu Data Frame

In [22]:
df_titanic.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   pclass    1309 non-null   int64
 1   survived  1309 non-null   int64
 2   name      1309 non-null   object
 3   sex       1309 non-null   object
 4   age       1046 non-null   float64
 5   sibsp     1309 non-null   int64
 6   parch     1309 non-null   int64
 7   ticket    1309 non-null   object
 8   fare      1308 non-null   float64
 9   cabin     295 non-null    object
 10  embarked  1307 non-null   object
dtypes: float64(2), int64(4), object(5)
memory usage: 409.5 KB

In [23]:
df_iris.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 15.1 KB

Memantau penggunaan memory untuk setiap kolom dari suatu Data Frame

In [24]:
df_titanic.memory_usage(deep=True)

Index         132
pclass      10472
survived    10472
name        99655
sex         70309
age         10472
sibsp       10472
parch       10472
ticket      73030
fare        10472
cabin       48006
embarked    65414
dtype: int64

In [25]:
df_iris.memory_usage(deep=True)

Index             132
Id               1200
SepalLengthCm    1200
SepalWidthCm     1200
PetalLengthCm    1200
PetalWidthCm     1200
Species          9350
dtype: int64

Materi 23: Seleksi baris pada Data Frame dengan query()

Import Modules

In [26]:
import pandas as pd

print(pd.__version__)

2.3.3

Persiapan Data Frame

In [27]:
d = {'kolom_satu':[1, 2, 3, 4, 5], 
     'kolom dua':[10, 20, 30, 40, 50]}
df = pd.DataFrame(d)
df

   kolom_satu  kolom dua
0           1         10
1           2         20
2           3         30
3           4         40
4           5         50

Seleksi baris dengan query()

In [28]:
df.query('kolom_satu > 2')

   kolom_satu  kolom dua
2           3         30
3           4         40
4           5         50

In [29]:
df.query('`kolom dua` > 30')

   kolom_satu  kolom dua
3           4         40
4           5         50

Materi 24: UTC dan konversi zona waktu (time zone) pada Python Pandas

Import Modules

In [30]:
import pandas as pd

print(pd.__version__)

2.3.3

Persiapan Series

In [31]:
s = pd.Series(range(1591683521, 1592201921, 3600))
s = pd.to_datetime(s, unit='s')
s.head()

0   2020-06-09 06:18:41
1   2020-06-09 07:18:41
2   2020-06-09 08:18:41
3   2020-06-09 09:18:41
4   2020-06-09 10:18:41
dtype: datetime64[ns]

Pengaturan zona waktu (time zone)

In [32]:
s = s.dt.tz_localize('UTC')
s.head()

0   2020-06-09 06:18:41+00:00
1   2020-06-09 07:18:41+00:00
2   2020-06-09 08:18:41+00:00
3   2020-06-09 09:18:41+00:00
4   2020-06-09 10:18:41+00:00
dtype: datetime64[ns, UTC]

In [33]:
s = s.dt.tz_convert('Asia/Jakarta')
s.head()

0   2020-06-09 13:18:41+07:00
1   2020-06-09 14:18:41+07:00
2   2020-06-09 15:18:41+07:00
3   2020-06-09 16:18:41+07:00
4   2020-06-09 17:18:41+07:00
dtype: datetime64[ns, Asia/Jakarta]

In [34]:
s = s.dt.tz_convert('Australia/Hobart')
s.head()

0   2020-06-09 16:18:41+10:00
1   2020-06-09 17:18:41+10:00
2   2020-06-09 18:18:41+10:00
3   2020-06-09 19:18:41+10:00
4   2020-06-09 20:18:41+10:00
dtype: datetime64[ns, Australia/Hobart]