Materi 13: Konversi nilai numerik ke dalam sejumlah kategori

Import Modules

In [3]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.3.5

Persiapan Data Frame

In [4]:
n_rows = 10
n_cols = 1
cols = ('usia',)

df = pd.DataFrame(np.random.randint(1, 99, size=(n_rows, n_cols)), 
                  columns=cols)
df

   usia
0    30
1    71
2    17
3    84
4    77
5    57
6    23
7    30
8    27
9    87

Pengelompokkan nilai numerik ke dalam beberapa kategori menggunakan cut()

In [5]:
df['kelompok_usia'] = pd.cut(df['usia'], 
                             bins=[0, 18, 65, 99], 
                             labels=['anak', 'dewasa', 'manula'])
df

   usia kelompok_usia
0    30        dewasa
1    71        manula
2    17          anak
3    84        manula
4    77        manula
5    57        dewasa
6    23        dewasa
7    30        dewasa
8    27        dewasa
9    87        manula

Materi 14: Menggabungkan (Merge) dua Data Frame

Import Modules

In [6]:
import pandas as pd
import numpy as np

print(pd.__version__)
print(np.__version__)

2.3.3
2.3.5

Persiapan Data Frame

In [7]:
n_rows = 5
n_cols = 5
cols = tuple('ABCDE')

df = pd.DataFrame(np.random.randint(1, 20, size=(n_rows, n_cols)), 
                  columns=cols)
df

    A   B   C   D   E
0   7   3  10  14  14
1  10  14   4  13   5
2   3  15  14   1   1
3   8  13   3  19  18
4  10   7   1  18  19

In [8]:
df1 = df.copy(deep=True)
df1 = df1.drop([1, 4])
df1

   A   B   C   D   E
0  7   3  10  14  14
2  3  15  14   1   1
3  8  13   3  19  18

In [9]:
df2 = df.copy(deep=True)
df2 = df2.drop([0, 3])
df2

    A   B   C   D   E
1  10  14   4  13   5
2   3  15  14   1   1
4  10   7   1  18  19

Menggabungkan dua Data Frame

In [10]:
df_inner = pd.merge(df1, df2, how='inner')
df_inner

   A   B   C  D  E
0  3  15  14  1  1

In [11]:
df_outer = pd.merge(df1, df2, how='outer')
df_outer

    A   B   C   D   E
0   3  15  14   1   1
1   7   3  10  14  14
2   8  13   3  19  18
3  10   7   1  18  19
4  10  14   4  13   5

Materi 15: Memecah nilai string dari suatu kolom ke dalam beberapa kolom baru

Import Modules

In [12]:
import pandas as pd
print(pd.__version__)

2.3.3

Persiapan Data Frame

In [13]:

data = {'nama':['Didi Kempot', 'Glenn Fredly', 'Mbah Surip'], 
        'tempat_kelahiran':['Surakarta, Jawa Tengah', 'Jakarta, DKI Jakarta', 'Mojokerto, Jawa Timur']}
df = pd.DataFrame(data)
df

           nama        tempat_kelahiran
0   Didi Kempot  Surakarta, Jawa Tengah
1  Glenn Fredly    Jakarta, DKI Jakarta
2    Mbah Surip   Mojokerto, Jawa Timur

Memecah nama depan dan nama belakang

In [14]:
df[['nama_depan', 'nama_belakang']] = df['nama'].str.split(' ', expand=True)
df

           nama        tempat_kelahiran nama_depan nama_belakang
0   Didi Kempot  Surakarta, Jawa Tengah       Didi        Kempot
1  Glenn Fredly    Jakarta, DKI Jakarta      Glenn        Fredly
2    Mbah Surip   Mojokerto, Jawa Timur       Mbah         Surip

Memecah nama kota dan propinsi

In [15]:
df[['kota', 'propinsi']] = df['tempat_kelahiran'].str.split(',', expand=True)
df

,nama,tempat_kelahiran,nama_depan,nama_belakang,kota,propinsi
0,Didi Kempot,"Surakarta, Jawa Tengah",Didi,Kempot,Surakarta,Jawa Tengah
1,Glenn Fredly,"Jakarta, DKI Jakarta",Glenn,Fredly,Jakarta,DKI Jakarta
2,Mbah Surip,"Mojokerto, Jawa Timur",Mbah,Surip,Mojokerto,Jawa Timur

Materi 16: Menata ulang Data Frame dengan mutiple indexes menggunakan unstack()

Import Modules

In [16]:
import pandas as pd
print(pd.__version__)

2.3.3

Persiapan Data Frame

In [18]:
df = pd.read_csv('titanicfull.csv')
df.head()

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S


Data Frame dengan multiple indexes dari hasil groupping

In [19]:
df.groupby(['sex', 'pclass'])['survived'].mean().to_frame()

               survived
sex    pclass
female 1       0.965278
       2       0.886792
       3       0.490741
male   1       0.340782
       2       0.146199
       3       0.152130

Menata ulang Data Frame dengan mutiple indexes

In [21]:
df.groupby(['sex', 'pclass'])['survived'].mean().unstack()

pclass         1         2         3
sex
female  0.965278  0.886792  0.490741
male    0.340782  0.146199  0.152130